---
name: go-ci

on:
  workflow_call: {}

jobs:
  goci:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    concurrency:
      group: go-ci-goci-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
    env:
      MISE_ENV: ci
    steps:
      - uses: hugoh/gh-workflows/setup@7cbb8fcf3a59c29229d6fd9feb02e46e0a02113a # v1.40.3
      - uses: $/go-mod-cache
      - name: Mise CI
        run: mise ci
        env:
          MISE_TASK_TIMINGS: true
