---
name: go-hk

on:
  workflow_call: {}

jobs:
  hk:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    concurrency:
      group: go-hk-hk-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
    steps:
      - name: Checkout code with full history
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
      - name: hk checks
        run: hk check --no-progress --profile ci --all --no-fail-fast
      - name: Display hk log on failure
        if: failure()
        run: cat /home/runner/.local/state/hk/output.log
