---
name: go-hk

on:
  workflow_call: {}

jobs:
  hk:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    concurrency:
      group: go-hk-hk-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
    steps:
      - uses: hugoh/gh-workflows/setup@def9793db21b497f44589cf409bc7d212166abc3 # v1.13.0
        with:
          fetch-depth: 0
      - uses: hugoh/gh-workflows/hk-check@def9793db21b497f44589cf409bc7d212166abc3 # v1.13.0
        env:
          PINACT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
